### ISSUE TITLE
Bug Report: Tesla Software Update 2023.38.* breaks Teslamate connection

### ISSUE THREAD

**Issue by imthefrizzlefry** [matt-FFFFFF/hassio-addon-teslamate#111]
**Describe the bug**

After upgrading my tesla to version 2023.38.4, Teslamate is no longer able to record data from my car.  There is a related issue on TeslaMate to cover this: https://github.com/adriankumpf/teslamate/issues/3371

It appears there is a patch to fix this issue, but no word on when TeslaMate will push an update. 

**Steps to reproduce**

1. Upgrade Tesla to 2023.38.*
2. Teslamate is no longer able to connect.

**Screenshots**

<img width="1090" alt="Screenshot 2023-10-27 at 21 39 01" src="https://github.com/matt-FFFFFF/hassio-addon-teslamate/assets/8007606/0f94e2b7-95d3-4b1d-ad09-e7af91b4b6f5">

**Comment by matt-FFFFFF** [comment]
Thanks for the heads up. I'll await an upstream fix and make another release

**Comment by imthefrizzlefry** [comment]
Thank you, I wouldn't ask for anything more!

**Comment by joaquinsfy** [comment]
It's possible meanwhile to use some patched repo?

docker pull jsightler/teslamate:20231029

I have pushed a build as well: https://hub.docker.com/repository/docker/jsightler/teslamate/general

This is based on this PR: https://github.com/adriankumpf/teslamate/pull/3373

My previous version broke some things as I misunderstood elixir pattern matching. I think this one might be a little better.
docker pull jsightler/teslamate:20231029

it seems to work great

**Comment by imthefrizzlefry** [comment]
I can confirm it works for me.  I stood of a temporary instance with it so
I can still collect data.

**Comment by matt-FFFFFF** [comment]
If you pull the image and tag correctly then you may achieve a successful outcome.

I will wait for the official upstream version to be fixed I think.

**Comment by joaquinsfy** [comment]
@matt-FFFFFF how can I tag the image to pull?

**Comment by TheDK** [comment]
@matt-FFFFFF There has been no feedback from Adrian at Teslmate for quite some time, so it does not appear that a fix is imminent. Would you mind temporarily using fixed version mentioned above? Feedback is positiv on the issues at the original feedback.

Thanks!

**Comment by NeWoKiKi** [comment]
Hi,

I received Tesla update yersterday, I'm now using 2023.38.6 and since this, I don't receive data anymore.
@TheDK found a fix as Adrian is missing for a while and just like him, I don't think that we'll have an update soon.

Is it possible to create a temporary fork maybe ? Instead of updating original one for the moment ?

Many thanks for your work,

**Comment by matt-FFFFFF** [comment]
Hi,

I think given the situation I can switch to the alternative source above. Let me have a look.

**Comment by Kev1000000** [comment]
> Hi,
> 
> I think given the situation I can switch to the alternative source above. Let me have a look.

That would be WONDERFUL.  Thank you for looking into this!

**Comment by jaymunro** [comment]
Thank you Matt. It does seem Adrian is otherwise occupied or unavailable.
https://github.com/adriankumpf/teslamate/issues/3399

**Comment by dsvirdiau** [comment]
Thank you Matt for looking into it. Cheers

**Comment by coreGreenberet** [comment]
@matt-FFFFFF that would be wonderful. I have the new version for 2 days now and it is really a pain on the ass to open/close the garage door via the fob😂

**Comment by TheDK** [comment]
@matt-FFFFFF Adrian posted (https://github.com/teslamate-org/teslamate/discussions/3384#discussioncomment-7546999) that he will release an update to get TM working again, but will not futher develop it and welcomes forks.

Even though he doesn't state when he plans to release the update, I hope that it will be rather soon, so maybe wait for that, release an update for the add-on based on Adrian's original repo which buys some time so decide what upstream source to pivot to? There seem to be a number of people willing to keep it running...

**Comment by TheDK** [comment]
…and new release is out. :)

**Comment by matt-FFFFFF** [comment]
Fixed by #114

**Comment by dsvirdiau** [comment]
Legend!

**Comment by TheDK** [comment]
Thanks Matt!
