### ISSUE TITLE
Bump upstream to v1.27.4

### ISSUE THREAD

**Issue by goebelmeier** [matt-FFFFFF/hassio-addon-teslamate#113]
Teslamate 1.27.3 is incompatible with the latest API changes for vehicles with installed vehicle software 2023.38.

https://github.com/teslamate-org/teslamate/issues/3393

1.27.4 restores compatibility and was just released. Please bump this addon to the most recent Teslamate version.

https://github.com/teslamate-org/teslamate/tree/v1.27.4

**Comment by matt-FFFFFF** [comment]
Fixed by #114
