### ISSUE TITLE
Bad update to hassio

### ISSUE THREAD

**Issue by dragorex71** [matt-FFFFFF/hassio-addon-teslamate#116]
I have hassio on 2023.11.2, Teslamate on 1.27.4 and my Tesla is on 2023.38.6
As you can see in the screenshot teslamate has access to my tesla.
My grafana is perfectly updated, it shows last datas and everythings is fine.
But, as you can se in the second screenshot, the log of the addon, there is something wrong. The result is that my mqtt sensors have no update and i can't use them.
When i listen events on mqtt at the topic teslamate/cars/1/# the reads are present but outdated: things like odometer, battery range, soc, etc. are old and different, obviusly, from the datas in the first screenshot for example.

Important notice is that before the upgrade of tesla to 2023.38.6 and, consequently, the upgrade of the addon, everythings was fine.

**Screenshots**
![image](https://github.com/matt-FFFFFF/hassio-addon-teslamate/assets/57069335/8acf8e37-1781-475d-bf20-48680328d72f)

![image](https://github.com/matt-FFFFFF/hassio-addon-teslamate/assets/57069335/b2c621e1-1b29-4a56-b70b-5465fe4052c3)

**Comment by dragorex71** [comment]
Problem solved, sorry!

**Comment by matt-FFFFFF** [comment]
What was the issue?

**Comment by dragorex71** [comment]
I had a second instance of teslamate in another Raspberry that I had forgotten about, It was a test before setup in hassio. I don't know how but mqtt in hassio connected to both. The other instance was not updated and therefore remained at last readings before the tesla update.
