### ISSUE TITLE
Cannot import Grafana dashboards

### ISSUE THREAD

**Issue by msvinth** [matt-FFFFFF/hassio-addon-teslamate#26]
I am not able to get importing of the Grafana dashboards to work.
If I set grafana_import_dashboards to true the TeslaMate add-on fails to start with this in the log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:28:11] INFO: Checking for Grafana folder: TeslaMate
jq: error (at <stdin>:0): Cannot index string with string "title"
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

The Grafana community add-on is configured as
```
plugins: []
env_vars:
  - name: GF_SECURITY_ADMIN_USER
    value: admin
  - name: GF_SECURITY_ADMIN_PASSWORD
    value: mysecretpassword
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
```

And in TeslaMate addon:

```
grafana_import_dashboards: true
grafana_folder_name: TeslaMate
grafana_host: a0d7b954-grafana
grafana_port: 3000
grafana_user: admin
grafana_pass: mysecretpassword
```

Grafana add-on has this in the logs so it seems like the configured user/password is not working even if configured literally as above:
```
t=2021-02-26T13:28:11+0100 lvl=eror msg="invalid username or password" logger=context error="invalid username or password"
t=2021-02-26T13:28:11+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/folders status=401 remote_addr=172.30.33.14 time_ms=23 size=42 referer=
```

If I set grafana_import_dashboards to false the TeslaMate addon starts up fine and also publishes to MQTT as expected.

**Comment by matt-FFFFFF** [comment]
Hi,

When Grafana starts do you see something similar in the log file?

```text
[12:59:34] INFO: Starting Grafana...
[12:59:34] INFO: Setting GF_SECURITY_ADMIN_USER to admin
[12:59:34] INFO: Setting GF_SECURITY_ADMIN_PASSWORD to mysecretpassword
```

Have you get `grafana_ingress_user:` in the Grafana options?

**Comment by msvinth** [comment]
Yes I have this in Grafana:
```
[13:27:53] INFO: Starting Memcached...
[13:27:54] INFO: Starting Grafana...
[13:27:54] INFO: Setting GF_SECURITY_ADMIN_USER to admin
[13:27:54] INFO: Setting GF_SECURITY_ADMIN_PASSWORD to mysecretpassword
t=2021-02-26T13:27:54+0100 lvl=info msg="Starting Grafana" logger=server version=7.4.2 commit=29e75ad97b branch=HEAD compiled=2021-02-17T12:39:25+0100
t=2021-02-26T13:27:54+0100 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-02-26T13:27:54+0100 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-02-26T13:27:54+0100 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=admin"
t=2021-02-26T13:27:54+0100 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
```

I have not set grafana_ingress_user.

**Comment by matt-FFFFFF** [comment]
Maybe try exposing the Grafana addon to the outside world using the Network config of the addon. Port 3000 should be free. You can then try connecting to http://yourhomeassistanthost:3000/ and try logging in - or using `curl` to test API access. See the https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/main/scripts/dashboards.sh script for the syntax.

At the moment this seems to be an issue with the Grafana addon not accepting the given password. I wonder if there are complexity requirements?

**Comment by msvinth** [comment]
I tried that and was not able to login with the credentials there as well.
I then uninstalled the Grafana add-on and installed and configured it again and now it works.
Not sure what happened there.
Sorry for the trouble and thanks a lot for this add-on!

**Comment by matt-FFFFFF** [comment]
No worries 😃 I read in the Grafana docs that the admin password is only set at initialisation time. This might be why it worked when you re-installed the addon. One for the docs maybe.
