### ISSUE TITLE
Upgrade to 1.21.6

### ISSUE THREAD

**Issue by tleegaard** [matt-FFFFFF/hassio-addon-teslamate#27]
Hi!
Is it possible for you to upgrade your repo to [1.21.6](https://github.com/adriankumpf/teslamate/releases/tag/v1.21.6)?
I'm seeing auth requests timing out on 1.21.5 and hope this wil fix it :-)
/Troels

**Comment by matt-FFFFFF** [comment]
This is building now, should be up soon! Thanks for the reminder
