### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by vasarat1** [matt-FFFFFF/hassio-addon-teslamate#38]
**Describe the bug**
Opening the add-on presents a login prompt, but the screen is frozen. The page seems to be refreshing periodically, and accepts no input in the login text boxes. Navigating to settings and geo-fencing menus is possible. If left hanging, the add-on crashes.

Possibly related to the following issue, fixable by updating TM version?: https://github.com/adriankumpf/teslamate/issues/1806

Add-on log has following message:
2021-08-11 18:28:02.211 [info] GET /sign_in
2021-08-11 18:28:02.221 [info] Sent 200 in 10ms
2021-08-11 18:28:02.582 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (267.799 ms)
2021-08-11 18:28:02.600 [error] GenServer TeslaMate.Api terminating
** (FunctionClauseError) no function clause matching in Regex.match?/2
    (elixir 1.12.1) lib/regex.ex:279: Regex.match?(~r/^https?:\/\//i, ["/captcha"])
    (tesla 1.4.1) lib/tesla/middleware/core.ex:34: Tesla.Middleware.BaseUrl.apply_base/2
    (tesla 1.4.1) lib/tesla/middleware/core.ex:29: Tesla.Middleware.BaseUrl.call/3
    (teslamate 1.23.4) lib/tesla_api/middleware/follow_redirects.ex:51: TeslaApi.Middleware.FollowRedirects.redirect/4
    (teslamate 1.23.4) lib/tesla_api/auth.ex:194: TeslaApi.Auth.load_captcha_image/2
    (teslamate 1.23.4) lib/tesla_api/auth.ex:183: TeslaApi.Auth.load_form/2
    (teslamate 1.23.4) lib/tesla_api/auth.ex:97: TeslaApi.Auth.prepare_login/0
    (teslamate 1.23.4) lib/teslamate/api.ex:122: TeslaMate.Api.handle_call/3
Last message (from #PID<0.2434.0>): :prepare_sign_in
2021-08-11 18:28:02.602 [error] GenServer #PID<0.2434.0> terminating
** (stop) exited in: GenServer.call(TeslaMate.Api, :prepare_sign_in, 120000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Regex.match?/2
            (elixir 1.12.1) lib/regex.ex:279: Regex.match?(~r/^https?:\/\//i, ["/captcha"])
            (tesla 1.4.1) lib/tesla/middleware/core.ex:34: Tesla.Middleware.BaseUrl.apply_base/2
            (tesla 1.4.1) lib/tesla/middleware/core.ex:29: Tesla.Middleware.BaseUrl.call/3
            (teslamate 1.23.4) lib/tesla_api/middleware/follow_redirects.ex:51: TeslaApi.Middleware.FollowRedirects.redirect/4
            (teslamate 1.23.4) lib/tesla_api/auth.ex:194: TeslaApi.Auth.load_captcha_image/2
            (teslamate 1.23.4) lib/tesla_api/auth.ex:183: TeslaApi.Auth.load_form/2
            (teslamate 1.23.4) lib/tesla_api/auth.ex:97: TeslaApi.Auth.prepare_login/0
            (teslamate 1.23.4) lib/teslamate/api.ex:122: TeslaMate.Api.handle_call/3
    (elixir 1.12.1) lib/gen_server.ex:1024: GenServer.call/3
    (teslamate 1.23.4) lib/teslamate_web/live/signin_live/index.ex:121: TeslaMateWeb.SignInLive.Index.handle_info/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:248: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :prepare_sign_in

**Steps to reproduce**

1. Install add-on per instructions.
2. Launch add-on
3. Open add-on web interface

**Screenshots**
![Screenshot from 2021-08-11 18-36-23](https://user-images.githubusercontent.com/58185915/129059625-943ba022-dbbb-4271-83f0-35ac3b1e7c64.png)

**Comment by matt-FFFFFF** [comment]
Thanks for reporting, haev started a build of 1.23.7 now and will create a new release if it works

**Comment by BartThoen** [comment]
Any updates on the new release?

**Comment by matt-FFFFFF** [comment]
Running now, shoudl be uploaded soon:

https://github.com/matt-FFFFFF/hassio-addon-teslamate/actions/runs/1139096939
