### ISSUE TITLE
Nothing in the map panel

### ISSUE THREAD

**Issue by ldb2000** [matt-FFFFFF/hassio-addon-teslamate#40]
**Describe the bug**
No thing showing in the map panel.

I have creating a docker-compose and import all the same data, and I can see everything.

What am I doing wrong ? 

The panel is showing a an empty (no trace) of the world map.

**Comment by matt-FFFFFF** [comment]
Hi this is due to the official grafana addon not supporting third party addon repos. I might consider creating a fork to allow this
