### ISSUE TITLE
bump version?

### ISSUE THREAD

**Issue by ohadlevy** [matt-FFFFFF/hassio-addon-teslamate#41]
Hello,

Would it be possible to update to 1.4.2 version? It includes a fix to certificate that expires today.

Also, I'll be happy to give it a shot, is the process documented somewhere?

**Comment by matt-FFFFFF** [comment]
Hi, happy to do this tonight. Needs to be changed by a repo member as otherwise the GitHub Actions don't run.

**Comment by matt-FFFFFF** [comment]
See #42 in progress

**Comment by matt-FFFFFF** [comment]
0.14.0 released
