### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by httpedo13** [matt-FFFFFF/hassio-addon-teslamate#51]
**Describe the bug**
[21:42:25] INFO: Checking for Grafana folder: TeslaMate
jq: error (at <stdin>:3): Cannot index string with string "title"
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.

**Screenshots**
![Schermata 2021-12-20 alle 22 44 37](https://user-images.githubusercontent.com/40502451/146836674-79387ed9-8fe9-4d69-ba59-ece91903e13d.png)

**Comment by Till--H** [comment]
Issue might come from incorrect configuration of Grafana.
Can you re-check if you performed the steps from https://github.com/matt-FFFFFF/hassio-addon-teslamate#automatically-uploading-grafana-dashboards (the Grafana config, i.e., the password needs be present before **very first** start of the Grafana plugin to take effect)

**Comment by httpedo13** [comment]
Thanks! the problem was that I had started the add on and then configured the user and password
