### ISSUE TITLE
Unable to use web ui

### ISSUE THREAD

**Issue by waraileron** [matt-FFFFFF/hassio-addon-teslamate#58]
**Describe the bug**
Since updating to Release v0.17.1, web ui is unusable (changing settings, creating geofence) with loading cursor constantly refreshing page.
Last known working Release v0.15.0
No error in logs, other than being unable to create geofence data collection still works.

Troubleshooting steps taken so far:
- Reinstall add on
- New instance on another off site raspberry pi4 HassOS

**Comment by faeton** [comment]
Same situation. Webdebug have shown that main page requests **ws://host:port/api/websocket** which results in 101 - switching protocols - and then it keeps trying **ws://host:port/live/websocket** which returns 404

**Comment by faeton** [comment]
My amateur URL analysis have shown (on my example) that teslamate addon page loads from (initial page) **http://10.0.0.10:8123/api/hassio_ingress/HTJsFDkeUzbcPJ5J9e6GEA99YQzYqIvdWfIGeija_70/sign_in** and so trying to add ingress path to websocket URL gets us back a correct reply here **ws://10.0.0.10:8123/api/hassio_ingress/HTJsFDkeUzbcPJ5J9e6GEA99YQzYqIvdWfIGeija_70/live/websocket** but how to fix that in code or redirect locally?

**Comment by faeton** [comment]
Ok, so I checked my theory and manually fixed 2 "/live" mentions in ~/lib/teslamate-1.26.1/priv/static/assets/app.js which made it work. But it's a temporary measure I wonder why it is not fixed withing Nginx replace [here](https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/main/services/nginx/teslamate.conf)

**Comment by matt-FFFFFF** [comment]
Hi @faeton, can you describe the change you made to the `app.js` file to get it to work please?

**Comment by faeton** [comment]
> Hi @faeton, can you describe the change you made to the `app.js` file to get it to work please?

Matt, there are 2 mentions of '"/live" in app.js, I've changed both to my ingress url - /api/hassio_ingress/HTJsFDkeUzbcPJ5J9e6GEA99YQzYqIvdWfIGeija_70/live (which is unique per user or not, i'm not sure). That is something meant to be achieved with **sub_filter '"/live"' '"$http_x_ingress_path/live"'** but it is not working I cannot find why.

Also clicking "home" text link in settings/geo tabs opens homeassistant within homeassistants iframe while clicking the teslamate logo works properly.

**Comment by elic1973** [comment]
I have the same issue. Any plan to have quick fix on it?

**Comment by matt-FFFFFF** [comment]
> Also clicking "home" text link in settings/geo tabs opens homeassistant within homeassistants iframe while clicking the teslamate logo works properly.

This is a known issue unfortunately

**Comment by matt-FFFFFF** [comment]
> > Hi @faeton, can you describe the change you made to the `app.js` file to get it to work please?
> 
> Matt, there are 2 mentions of '"/live" in app.js, I've changed both to my ingress url - /api/hassio_ingress/HTJsFDkeUzbcPJ5J9e6GEA99YQzYqIvdWfIGeija_70/live (which is unique per user or not, i'm not sure). That is something meant to be achieved with **sub_filter '"/live"' '"$http_x_ingress_path/live"'** but it is not working I cannot find why.

Thank you, I'll see if I can do anything with a `sed` hack before teslamate starts. It's not pretty but...

**Comment by matt-FFFFFF** [comment]
A bit like this:

https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/ea05e211fb29529393ec13a0de2ecee712b2e8f3/services/teslamate/run#L8

**Comment by elic1973** [comment]
@matt-FFFFFF any solution soon? I had to change my tokens and now I can not use teslamate.

**Comment by elic1973** [comment]
> @matt-FFFFFF any solution soon? I had to change my tokens and now I can not use teslamate.

@matt-FFFFFF should I reinstall addon ? or delete repo and pull again?

**Comment by matt-FFFFFF** [comment]
There's no update I'm afraid. I have tried to automate the patching of app.js but I can't get it to work.

Still working on it.

If you need to update the token then I'd suggest updating the database directly.

**Comment by elic1973** [comment]
> There's no update I'm afraid. I have tried to automate the patching of app.js but I can't get it to work.
> 
> Still working on it.
> 
> If you need to update the token then I'd suggest updating the database directly.

@matt-FFFFFF how can I update the DB? could you please instruct how to do so ?

**Comment by elic1973** [comment]
> > There's no update I'm afraid. I have tried to automate the patching of app.js but I can't get it to work.
> > Still working on it.
> > If you need to update the token then I'd suggest updating the database directly.
> 
> @matt-FFFFFF how can I update the DB? could you please instruct how to do so ?

ok, I managed to update the DB directly. now it seems to work.

**Comment by elic1973** [comment]
@matt-FFFFFF any chance for a fix? I need to set up a geofence, is there also a possibility to add to the DB? if yes how should I do it?.

**Comment by faeton** [comment]
Fixed, submitted a pull request.

**Comment by matt-FFFFFF** [comment]
Thank you :)

Building now

**Comment by waraileron** [comment]
Works great!
Thanks @faeton, @matt-FFFFFF !!!
Closing
