### ISSUE TITLE
mqtt_namespace required in config, but not required actually

### ISSUE THREAD

**Issue by faeton** [matt-FFFFFF/hassio-addon-teslamate#61]
User interface or config-default issue?
And what is the "Network" block?

**Comment by matt-FFFFFF** [comment]
Hi,

my `mqtt_namespace` is blank and it works fine.

The network block may be there because of the empty `ports` object in the config. It isn't required as ingress is now used.

**Comment by matt-FFFFFF** [comment]
If you had multiple instances of Teslamate running, you would need to use MQTT namespace.
