### ISSUE TITLE
Automations already running.

### ISSUE THREAD

**Issue by chicagoandy** [matt-FFFFFF/hassio-addon-teslamate#62]
The example automation at : https://docs.teslamate.org/docs/integrations/home_assistant/ does not specify a mode for the "Update Tesla location" automation.    HomeAssistant has defaulted this to 'single', and I am getting many errors in the logs.

Logger: homeassistant.components.automation.tesla_updatelocation
Source: helpers/script.py:1375
Integration: Automation (documentation, issues)
First occurred: February 27, 2022, 12:21:55 AM (16294 occurrences)
Last logged: 8:17:15 AM

Tesla: UpdateLocation: Already running

What is the recommended mode for this automation?   I would think that Single would work as the action should be rather quick, but it is not.   Best to make this queued?  Parallel?

**Comment by matt-FFFFFF** [comment]
Hi, thanks for raising the issue.

I use this in my automation config:

```yaml
mode: single
max_exceeded: silent
```

**Comment by matt-FFFFFF** [comment]
Closing as no feedback
