### ISSUE TITLE
Import data from other TeslaMate setup

### ISSUE THREAD

**Issue by WayeeWang** [matt-FFFFFF/hassio-addon-teslamate#66]
This HA add-on is a great contribution. However, once have it up and running in HA, all history data of the vehicle (recorded by the original TeslaMate docker setup) are lost, which is a big pity. 

Teslamate does provide a backup and restore mechanism. Is it possible to provide an interface in this addon, to restore the database from a backup file?

Reference: https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by matt-FFFFFF** [comment]
Hi,

In this scenario it's the database that can be restored.

If you expose the Postgres addon's port externally, you can restore data.

Do you still have a copy of the old docket image you can use? I would recommend pgAdmin or similar to make the backup and restore easier.

**Comment by WayeeWang** [comment]
> 

Thanks a lot for pointing the direction. Could you please maybe instruct me a bit how to make the backup and restore it to the addon with Postgres port exposed?

**Comment by mnadvornik** [comment]
@WayeeWang do you still need help? Just migrated my database from my old docker container to the database of the addon in HASS. Just tell me where you are stuck and I am happy to help

**Comment by svanzon** [comment]
@mnadvornik I am starting with migrating from the regular install (docker) from https://docs.teslamate.org/docs/installation/docker to this version as addon in Home Assistant OS (standard instal).

I know how to make the back-up as described in the link above (and have the teslamate.bck file) but have no clue how to import it in Home Assistant OS. Normally I will follow the docs but this is not working as I don't have normal acces to SSH (do I need to use the SSH addon?).

**Comment by matt-FFFFFF** [comment]
Archiving
