### ISSUE TITLE
Cannot create Geofences from within Grafana

### ISSUE THREAD

**Issue by hscholing** [matt-FFFFFF/hassio-addon-teslamate#67]
The integration is running fine, but I cannot create a new Geofence from within Grafana. When trying it tries to reconnect to the TM link but doesn't work. Normally I would add the default URL in the settings of TM, but what is the right one? I could make a redirect to http://ip.address:4000 but the integration doesn't respond on IP port 4000 and I cannot add it in the configuration. 

So, what is the right URL to do so? I tried the URL HomeAssistant is showing, but this one is also not working for me: http://192.168.2.1:8123/hassio/ingress/29b65938_teslamate

**Comment by matt-FFFFFF** [comment]
Hi,

This is a known issue, due to the way that HA generates a dynamic URI entry point for the add on, it's difficult to set the correct URL to link back to a Tesla mate from Grafana.

Best bet is to go to the TM add on in the HA portal.
