### ISSUE TITLE
Documentation Update:  - ENCRYPTION_KEY

### ISSUE THREAD

**Issue by chicagoandy** [matt-FFFFFF/hassio-addon-teslamate#73]
Please update the documentation to indicate how to specify a custom encryption_key.  https://github.com/adriankumpf/teslamate/releases/tag/v1.27.0

**Comment by matt-FFFFFF** [comment]
Thanks for the issue - done!

**Comment by chicagoandy** [comment]
Dumb question: where?

**Comment by matt-FFFFFF** [comment]
Documented in the README, the value can be set in the add on configuration.
