### ISSUE TITLE
Feature Request - or question

### ISSUE THREAD

**Issue by askpet** [matt-FFFFFF/hassio-addon-teslamate#77]
I have been running Home Assistant and  Teslamate in Docker (Synology NAS) for years. Resently I moved to HA OS-  with supervisor. And therefore I want to move my postgres-data to new location. Any suggestions on how to do that?. I have exported my data to a bak file - but I am unsure on how to import the data to Postgres db. Any suggestions?

**Comment by matt-FFFFFF** [comment]
Hi,

If you add an external port mapping to the Postgres add on you can connect to it with tools like pgadmin. 

Using this you can restore the database.

**Comment by askpet** [comment]
Just to follow up: I ended up with installing pgAdmin add-on in HA. From that I connected to my org. database and backup up and restored. Nice. Now I just need to figure out how I link to specific Grafana pages. It does not work like before. But thats, at all, on your table :-). Thanks again for quick response

**Comment by askpet** [comment]
Closed as pr. prior comment
