### ISSUE TITLE
Charging Stats broken / plugin not found: natel-plotly-panel

### ISSUE THREAD

**Issue by mat1990dj** [matt-FFFFFF/hassio-addon-teslamate#78]
Similar to https://github.com/matt-FFFFFF/hassio-addon-teslamate/issues/74
The natel-plotly-panel is also missing.

![image](https://user-images.githubusercontent.com/5220059/201415531-355c0bf9-e1a2-413a-8a68-e94d7650bc67.png)

**Comment by Hufflepuff-source** [comment]
I have the same issue. I have added the plugins in the Grafana config and restarted the add on; but on the dashboards, they say plugin not found. :(

**Comment by llluis** [comment]
This is working for me.
Just add it to the grafana configuration and it will run fine:
```
plugins:
  - name: natel-discrete-panel
  - name: natel-plotly-panel
```
```
[01:16:20] INFO: Installing natel-discrete-panel
✔ Downloaded and extracted natel-discrete-panel v0.1.1 zip successfully to /var/lib/grafana/plugins/natel-discrete-panel
Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
[01:16:21] INFO: Installing natel-plotly-panel
✔ Downloaded and extracted natel-plotly-panel v0.0.7 zip successfully to /var/lib/grafana/plugins/natel-plotly-panel
Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
```
```
logger=plugin.loader t=2023-05-26T01:16:31.55872366-04:00 level=info msg="Plugin registered" pluginID=natel-discrete-panel
logger=plugin.loader t=2023-05-26T01:16:31.558790455-04:00 level=info msg="Plugin registered" pluginID=natel-plotly-panel
```

No error in dashboard:
![image](https://github.com/matt-FFFFFF/hassio-addon-teslamate/assets/708868/ad083856-d716-4a2c-8152-5a5a389c6cea)

**Comment by llluis** [comment]
This can also be closed, as it's a non-issue. The plugin works out of the box.
