### ISSUE TITLE
Open 80/443 ports to directly access TeslaMate

### ISSUE THREAD

**Issue by kegelmeier** [matt-FFFFFF/hassio-addon-teslamate#80]
**Describe the solution you'd like**

Within other add-ons you have control about the ports the Add-on is opening. 

Would be great to assign and open the 80/443 port of TeslaMate to directly access it without the need to go through HA.

**Comment by matt-FFFFFF** [comment]
This would bypass all authorisation so I'm not sure it's a great idea. You can run TeslaMate outside HA if you need this functionality.

**Comment by kegelmeier** [comment]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/28561266/214567846-3565da71-25f8-4d64-9eef-849fc694b2d8.png">

Risk is on the user's side for sure.
Attached is an image from another add-on (Zigbee2MQTT) that allows the expose of the port publically.
