### ISSUE TITLE
Unable to upload Grafana dashboards

### ISSUE THREAD

**Issue by pezlin** [matt-FFFFFF/hassio-addon-teslamate#89]
I believe I have followed the instructions but and are able to start both TeslaMate and Grafana Add-on. However, when I change the config on TeslaMate add-on to import dashboards I get the following error when trying to start TeslaMate add-on:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:28:29] INFO: Checking for Grafana folder: TeslaMate
jq: error (at <stdin>:1): Cannot index string with string "title"
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Any idea where to start looking?

**Comment by RealDeemer** [comment]
Hi, i have a fresh install here and experience exactly the same issue. I checked my settings and credentials for more than three times and cannot find any deviation in the config so far.

**Comment by pezlin** [comment]
> Hi, i have a fresh install here and experience exactly the same issue. I checked my settings and credentials for more than three times and cannot find any deviation in the config so far.

I reinstalled everything (TeslaMate, Postgre, Grafana) and now the dashboards are imported. I don't know what I did differently this time though.
