### ISSUE TITLE
Bug Report: Multiple Pings Per Second

### ISSUE THREAD

**Issue by ColoradoBills** [matt-FFFFFF/hassio-addon-teslamate#90]
I am working with Tesla due to multiple issues related to the main computer in our 2021 Model 3 LR. Tesla is saying a third-party "app," is sending up to 3,600 pings to our tesla per hour. I have disabled this addon and the Tesla Integration for Home Assistant. About 6 weeks ago, Tesla forced me to reset my password, and they remotely removed all third access to my account. I added back the previous mention of Home Assist items and TeslaFi. Has anyone else experienced this similar activity from either of these addon or the Tesla integration? Tesla is unable to show me proof of this issue they are saying is causing my computer to run out of memory every 4 to 6 weeks. Thank you in advance.

**Comment by matt-FFFFFF** [comment]
Hi this should perhaps be logged upstream on the TM repo. The HA addon wrapper should not affect the application's behaviour.
