### ISSUE TITLE
Some topics not published to MQTT

### ISSUE THREAD

**Issue by pezlin** [matt-FFFFFF/hassio-addon-teslamate#91]
When comparing the topics mentioned on [https://docs.teslamate.org/docs/integrations/mqtt](https://docs.teslamate.org/docs/integrations/mqtt) and what is published to MQTT when using the addon there are a few topics missing, like Model, Trim_badging and Version.

**Comment by matt-FFFFFF** [comment]
Hi I'm pretty sure this implementation isn't opinionated on the MQTT topics published. It just runs TM with the configuration variables.

If you want to test then spin up a teslamate instance outside home assistant and then connect it to the same MQTT server.

**Comment by pezlin** [comment]
Sorry, I forgot to close this issue. The topics appeared after a restart of the add-on.
