### ISSUE TITLE
After updating Operating System to 10.1 version, teslamate cannot start

### ISSUE THREAD

**Issue by raforo** [matt-FFFFFF/hassio-addon-teslamate#92]
Working fine until now, but after updating Operating System to 10.1 version, teslamate cannot start. Not other Home Assistant service affected, Grafana and Postgres are runing ok  

Versions:
TeslaMate AddOn Current version: 0.18.1  Teslamate 1.27.1 (not latest)
Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230411.1 - latest

Teslamate log:
[s6-init] making user provided files available at var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:56:34] INFO: Checking for Grafana folder: TeslaMate
[16:56:35] INFO: ... RESTORED timeline.json
[16:56:35] INFO: ... RESTORED statistics.json
[16:56:35] INFO: ... RESTORED projected-range.json
[16:56:36] INFO: ... RESTORED drives.json
[16:56:36] INFO: ... RESTORED charge-level.json
[16:56:36] INFO: ... RESTORED trip.json
[16:56:37] INFO: ... RESTORED updates.json
[16:56:37] INFO: ... RESTORED overview.json
[16:56:37] INFO: ... RESTORED charging-stats.json
[16:56:38] INFO: ... RESTORED vampire-drain.json
[16:56:38] INFO: ... RESTORED visited.json
[16:56:38] INFO: ... RESTORED mileage.json
[16:56:38] INFO: ... RESTORED drive-stats.json
[16:56:39] INFO: ... RESTORED efficiency.json
[16:56:39] INFO: ... RESTORED locations.json
[16:56:39] INFO: ... RESTORED states.json
[16:56:40] INFO: ... RESTORED charges.json
[16:56:40] INFO: ... RESTORED charge-details.json
[16:56:40] INFO: ... RESTORED drive-details.json
[16:56:40] INFO: Finished Importing Grafana Dashboards
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
Killed
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.

Supervisor log:
23-04-30 16:56:28 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TeslaMate is failed, restarting...
23-04-30 16:56:28 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_29b65938_teslamate application
23-04-30 16:56:30 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on mattffffff/teslamate-aarch64 with version 0.18.1
23-04-30 16:56:45 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-15211' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1003, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00

**Comment by guybw** [comment]
I just wanted to add that I have exactly the same issue.

**Comment by matt-FFFFFF** [comment]
Thanks for reporting. I'll try and reproduce. I haven't upgraded yet.

**Comment by agners** [comment]
OP posted another hint in the OS issue: https://github.com/home-assistant/operating-system/issues/2526

```
[ 164.964259] Out of memory: killed process 7400 (beam,smp) total-vm:3246464kB,anon-rss:1191984kB, file-rss:8kB, shmen-rss:0kB, UID:0 pgtables:2472kB oom_score_adj:200
```

This is most likely related to: https://developers.home-assistant.io/blog/2023/04/13/new_limits_for_add_ons

**Comment by matt-FFFFFF** [comment]
Good catch. Will integrate into the service start

**Comment by raforo** [comment]
I've erased teslamate Addon and I've reinstaled the new repository but fail remain, please tell me how can I fix it?

**Comment by matt-FFFFFF** [comment]
Hi, I haven't pushed the new build to production yet. I need to test it.

You can do the same by opening a privileged CLI on your HA host, pulling the `dev` tag and locally re-tagging it as the current version.

To use such a terminal I recommend the `Advanced SSH & Web Terminal` addon, with protection mode disabled. If you have done it correctly you will see this banner on the addon page:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/16320656/235769692-5d39179b-0256-4f06-a311-7b091d40ee7c.png">


First stop the TM addon. Then do this:

```bash
docker pull mattffffff/teslamate-amd64:dev
docker tag mattffffff/teslamate-amd64:dev mattffffff/teslamate-amd64:0.18.1
```

Then restart TM.

**Comment by raforo** [comment]
I'm sorry so much, but I cannot fix it, I've tried what you wrote but container doesn't start

➜  ~ docker pull mattffffff/teslamate-amd64:dev
dev: Pulling from mattffffff/teslamate-amd64
Digest: sha256:d9eb1bb3482c53969b7d3a917894dbe0da3caed7791386c5fd732a9237a46506
Status: Image is up to date for mattffffff/teslamate-amd64:dev
docker.io/mattffffff/teslamate-amd64:dev
➜  ~ docker tag mattffffff/teslamate-amd64:dev mattffffff/teslamate-amd64:0.18.1
➜  ~ docker start 046914370c9
046914370c9
➜  ~ docker ps -a
CONTAINER ID   IMAGE                                                           COMMAND                  CREATED          STATUS                        PORTS                                                                                                                          NAMES
046914370c9c   mattffffff/teslamate-aarch64:0.18.1                             "/init"                  13 minutes ago   Exited (129) 23 seconds ago                                                                                                                                  addon_29b65938_teslamate
b

**Comment by raforo** [comment]
I've realized my type is aarch64, not amd64. I've repeated the process with aarch64 and this time it work fine.

Thanks a lot

**Comment by matt-FFFFFF** [comment]
Thanks for verifying!

**Comment by guybw** [comment]
I can confirm the latest release fixed this for me as well, thanks for fixing so quickly !
